// src/ui/EmptyState.tsx
import type { ReactNode } from "react";

type Tone = "neutral" | "warn" | "danger";

interface Props {
  /** Big icon character / emoji shown inside the colored circle. */
  icon?: ReactNode;
  /** Bold heading line. */
  title: string;
  /** Optional supporting description below the title. */
  description?: ReactNode;
  /** Optional action node (button, etc.) below the description. */
  action?: ReactNode;
  tone?: Tone;
}

const ICON_BG: Record<Tone, string> = {
  neutral: "bg-surface/40 border border-edge text-fg-muted",
  warn: "bg-tint-warning border border-tint-warning-bd text-tint-warning-fg",
  danger: "bg-tint-danger border border-tint-danger-bd text-tint-danger-fg",
};

const DESC_COLOR: Record<Tone, string> = {
  neutral: "text-fg-muted",
  warn: "text-fg-muted",
  danger: "text-destructive",
};

/**
 * Centered empty / error state with optional icon + heading + description
 * + action. Lifts the repeated `flex items-center justify-center py-X
 * + max-w-md text-center space-y-2 + inline-flex h-10 w-10 rounded-full
 * border bg-...` pattern out of MainArea.
 */
export default function EmptyState({ icon, title, description, action, tone = "neutral" }: Props) {
  return (
    <div className="flex items-center justify-center py-8">
      <div className="max-w-md text-center space-y-2">
        {icon && (
          <div
            className={`inline-flex items-center justify-center h-10 w-10 rounded-full ${ICON_BG[tone]}`}
          >
            <span className="text-lg">{icon}</span>
          </div>
        )}
        <h2 className="text-base font-semibold text-fg">{title}</h2>
        {description && <p className={`text-sm ${DESC_COLOR[tone]}`}>{description}</p>}
        {action && <div className="pt-1">{action}</div>}
      </div>
    </div>
  );
}

// src/ui/EmptyState.vue
<script setup lang="ts">
/**
 * Use EmptyState when a list or panel has no content to show.
 * Provide #icon, #description, and/or #action slots as needed.
 */

import { computed, useSlots } from "vue";

type Tone = "neutral" | "warn" | "danger";

const props = withDefaults(
  defineProps<{
    title: string;
    tone?: Tone;
  }>(),
  {
    tone: "neutral",
  },
);

const slots = useSlots();

const ICON_BG: Record<Tone, string> = {
  neutral: "bg-surface/40 border border-edge text-fg-muted",
  warn: "bg-tint-warning border border-tint-warning-bd text-tint-warning-fg",
  danger: "bg-tint-danger border border-tint-danger-bd text-tint-danger-fg",
};

const DESC_COLOR: Record<Tone, string> = {
  neutral: "text-fg-muted",
  warn: "text-fg-muted",
  danger: "text-destructive",
};

const iconBg = computed(() => ICON_BG[props.tone!]);
const descColor = computed(() => DESC_COLOR[props.tone!]);
</script>

<template>
  <div class="flex items-center justify-center py-8">
    <div class="max-w-md text-center space-y-2">
      <div
        v-if="slots.icon"
        :class="`inline-flex items-center justify-center h-10 w-10 rounded-full ${iconBg}`"
      >
        <span class="text-lg"><slot name="icon" /></span>
      </div>
      <h2 class="text-base font-semibold text-fg">{{ title }}</h2>
      <p v-if="slots.description" :class="`text-sm ${descColor}`">
        <slot name="description" />
      </p>
      <div v-if="slots.action" class="pt-1">
        <slot name="action" />
      </div>
    </div>
  </div>
</template>
