// src/components/Popover.tsx
import { type ReactNode, useEffect, useRef, useState } from "react";

interface Props {
  /** Element rendered as the trigger; receives `onClick` + `aria-expanded`. */
  trigger: (props: { onClick: () => void; "aria-expanded": boolean }) => ReactNode;
  align?: "left" | "right";
  /** Tailwind width class (e.g. `w-60`, `w-80`). */
  widthClass?: string;
  children: ReactNode | ((close: () => void) => ReactNode);
}

/**
 * Small click-outside-to-dismiss popover. Click the trigger to toggle.
 * Children may be a render-prop receiving a `close()` for nested actions.
 */
export default function Popover({
  trigger,
  align = "right",
  widthClass = "w-60",
  children,
}: Props) {
  const [open, setOpen] = useState(false);
  const containerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!open) return;
    const onMouseDown = (e: MouseEvent) => {
      if (containerRef.current && !containerRef.current.contains(e.target as Node)) {
        setOpen(false);
      }
    };
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") setOpen(false);
    };
    document.addEventListener("mousedown", onMouseDown);
    document.addEventListener("keydown", onKey);
    return () => {
      document.removeEventListener("mousedown", onMouseDown);
      document.removeEventListener("keydown", onKey);
    };
  }, [open]);

  const close = () => setOpen(false);

  return (
    <div className="relative" ref={containerRef}>
      {trigger({ onClick: () => setOpen((v) => !v), "aria-expanded": open })}
      {open && (
        <div
          className={`absolute mt-1.5 ${widthClass} max-w-[calc(100vw-1rem)] rounded-lg border border-gray-700 bg-gray-900 shadow-xl p-3 z-30 ${
            align === "right" ? "right-0" : "left-0"
          }`}
          role="dialog"
        >
          {typeof children === "function" ? children(close) : children}
        </div>
      )}
    </div>
  );
}

// src/ui/Popover.vue
<script setup lang="ts">
/**
 * Use Popover for floating contextual panels anchored to a trigger element.
 * Bind the #trigger slot to your button; the default slot receives { close }.
 */

import { ref, watch, onUnmounted, nextTick } from "vue";

const props = withDefaults(
  defineProps<{
    align?: "left" | "right";
    widthClass?: string;
  }>(),
  {
    align: "right",
    widthClass: "w-60",
  },
);

const open = ref(false);
const containerRef = ref<HTMLElement | null>(null);

function toggle() {
  open.value = !open.value;
}

function close() {
  open.value = false;
}

function onMousedown(event: MouseEvent) {
  if (!open.value) return;
  if (
    containerRef.value &&
    !containerRef.value.contains(event.target as Node)
  ) {
    close();
  }
}

function onKeydown(event: KeyboardEvent) {
  if (open.value && event.key === "Escape") {
    close();
  }
}

watch(open, async (isOpen) => {
  if (isOpen) {
    await nextTick();
    document.addEventListener("mousedown", onMousedown);
    document.addEventListener("keydown", onKeydown);
  } else {
    document.removeEventListener("mousedown", onMousedown);
    document.removeEventListener("keydown", onKeydown);
  }
});

onUnmounted(() => {
  document.removeEventListener("mousedown", onMousedown);
  document.removeEventListener("keydown", onKeydown);
});

const bodyClasses = [
  "absolute mt-1.5 max-w-[calc(100vw-1rem)] rounded-lg border border-edge bg-overlay shadow-xl p-3 z-30",
];
</script>

<template>
  <div class="relative" ref="containerRef">
    <slot name="trigger" :toggle="toggle" :expanded="open" />
    <div
      v-if="open"
      :class="[...bodyClasses, widthClass, align === 'right' ? 'right-0' : 'left-0']"
      role="dialog"
    >
      <slot :close="close" />
    </div>
  </div>
</template>
