// src/components/ConnectionStatus.tsx
import { useEffect, useRef, useState } from "react";
import { validateCredentials, type BannerCredentials } from "../lib/api";
import { forceReauth } from "../lib/extension";
import Popover from "./Popover";

interface Props {
  onCredentials: (creds: BannerCredentials | null) => void;
  termLabel?: string | null;
  loading?: boolean;
}

export default function ConnectionStatus({ onCredentials, termLabel, loading }: Props) {
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [sessionAge, setSessionAge] = useState(0);
  const connectedAtRef = useRef<number | null>(Date.now());

  useEffect(() => {
    const id = setInterval(() => {
      if (connectedAtRef.current != null) {
        setSessionAge(Math.floor((Date.now() - connectedAtRef.current) / 1000));
      }
    }, 10000);
    return () => clearInterval(id);
  }, []);

  const stale = sessionAge >= 55 * 60;
  const ageMin = Math.floor(sessionAge / 60);
  const ageLabel = ageMin < 1 ? "just now" : `${ageMin}m ago`;

  const handleReauth = async (close: () => void) => {
    setError(null);
    setBusy(true);
    const result = await forceReauth();
    if (!result.ok || !result.credentials) {
      setBusy(false);
      setError(result.message ?? "Reauth failed");
      return;
    }
    const validation = await validateCredentials(result.credentials);
    setBusy(false);
    if (!validation.valid) {
      setError(validation.error ?? "Captured credentials are not valid");
      return;
    }
    connectedAtRef.current = Date.now();
    setSessionAge(0);
    onCredentials(result.credentials);
    close();
  };

  return (
    <Popover
      align="right"
      widthClass="w-60"
      trigger={({ onClick, "aria-expanded": expanded }) => (
        <button
          onClick={onClick}
          aria-expanded={expanded}
          className={`flex items-center gap-1.5 rounded-md px-2.5 py-1 text-xs transition-colors ${
            stale
              ? "bg-yellow-900/30 border border-yellow-700/60 text-yellow-300 hover:bg-yellow-900/50"
              : "bg-emerald-900/30 border border-emerald-800/60 text-emerald-300 hover:bg-emerald-900/50"
          }`}
        >
          <span className={`h-1.5 w-1.5 rounded-full ${stale ? "bg-yellow-400" : "bg-emerald-400"}`} />
          <span className="hidden sm:inline">Connected</span>
          {termLabel && <span className="text-emerald-400/70">· {termLabel}</span>}
          {loading && <span className="text-emerald-400/70 italic">· Loading…</span>}
        </button>
      )}
    >
      {(close) => (
        <div className="space-y-2">
          <div className="flex items-center justify-between text-xs">
            <span className="text-gray-400">Session age</span>
            <span className={stale ? "text-yellow-400" : "text-gray-200"}>{ageLabel}</span>
          </div>
          {stale && (
            <p className="text-[11px] text-yellow-400">
              Session may have expired. Reauth to refresh.
            </p>
          )}
          <button
            onClick={() => handleReauth(close)}
            disabled={busy}
            className="w-full rounded-md border border-gray-700 px-2.5 py-1.5 text-xs text-gray-300 hover:text-white hover:border-gray-500 disabled:opacity-40 disabled:cursor-not-allowed transition-colors"
          >
            {busy ? "Waiting for SAIT login…" : "Force Reauth"}
          </button>
          <button
            onClick={() => {
              onCredentials(null);
              close();
            }}
            className="w-full rounded-md px-2.5 py-1.5 text-xs text-gray-500 hover:text-red-400 transition-colors"
          >
            Disconnect
          </button>
          {error && <p className="text-[11px] text-red-400">{error}</p>}
        </div>
      )}
    </Popover>
  );
}

// src/features/auth/ConnectionStatus.vue
<script setup lang="ts">
/**
 * Connected-pill in the AppHeader. Shows term + loading badge inline; on
 * click opens a session menu with the age, a Reauth button, and a
 * Disconnect button. Tinted warn when the credentials are stale.
 */
import { useAuth } from "./useAuth";
import Popover from "@/ui/Popover.vue";
import StatusDot from "@/ui/StatusDot.vue";

defineProps<{
  termLabel?: string | null;
  loading?: boolean;
}>();

const { busy, error, isStale, sessionAgeSeconds, reauth, disconnect } = useAuth();

function ageLabel(s: number): string {
  const minutes = Math.floor(s / 60);
  return minutes < 1 ? "just now" : `${minutes}m ago`;
}

async function handleReauth(close: () => void): Promise<void> {
  const result = await reauth();
  if (result.ok) close();
}

async function handleDisconnect(close: () => void): Promise<void> {
  await disconnect();
  close();
}
</script>

<template>
  <Popover align="right" width-class="w-60">
    <template #trigger="{ toggle, expanded }">
      <button
        type="button"
        :aria-expanded="expanded"
        aria-haspopup="menu"
        :aria-label="`Connected to Banner${termLabel ? `, ${termLabel}` : ''}${loading ? ', loading' : ''} — open session menu`"
        :class="[
          'flex items-center gap-1.5 rounded-md px-2.5 py-1 text-xs transition-colors',
          isStale
            ? 'bg-tint-warning/90 border border-tint-warning-bd text-tint-warning-fg hover:bg-tint-warning'
            : 'bg-tint-success/90 border border-tint-success-bd text-tint-success-fg hover:bg-tint-success',
        ]"
        @click="toggle"
      >
        <StatusDot :tone="isStale ? 'warn' : 'ok'" />
        <span class="hidden sm:inline">Connected</span>
        <template v-if="termLabel">
          <span class="hidden sm:inline">·&nbsp;</span>
          <span>{{ termLabel }}</span>
        </template>
        <span v-if="loading" class="italic">· Loading…</span>
      </button>
    </template>
    <template #default="{ close }">
      <div class="space-y-2">
        <div class="flex items-center justify-between text-xs">
          <span class="text-fg-muted">Session age</span>
          <span :class="isStale ? 'text-warning' : 'text-fg'">
            {{ ageLabel(sessionAgeSeconds) }}
          </span>
        </div>
        <p v-if="isStale" class="text-[11px] text-warning">
          Session may have expired. Reauth to refresh.
        </p>
        <button
          type="button"
          :disabled="busy"
          class="w-full rounded-md border border-edge px-2.5 py-1.5 text-xs text-fg-muted hover:text-fg hover:border-edge-hover disabled:opacity-40 disabled:cursor-not-allowed transition-colors"
          @click="handleReauth(close)"
        >
          {{ busy ? "Waiting for SAIT login…" : "Force Reauth" }}
        </button>
        <button
          type="button"
          class="w-full rounded-md border border-tint-danger-bd bg-tint-danger px-2.5 py-1.5 text-xs text-tint-danger-fg hover:bg-destructive hover:text-destructive-fg hover:border-destructive transition-colors"
          @click="handleDisconnect(close)"
        >
          Disconnect
        </button>
        <p v-if="error" class="text-[11px] text-destructive">{{ error }}</p>
      </div>
    </template>
  </Popover>
</template>
