// src/features/auth/ExtensionIdSettings.tsx
import { useEffect, useState } from "react";
import {
  getExtensionId,
  isExtensionContext,
  setExtensionId,
  subscribeExtensionId,
} from "../../lib/extensionId";

/**
 * Lets the user view / paste the chrome extension ID when the app is running
 * outside the extension (dev server, AI, pages.dev). Hidden when running as
 * the extension's own page since the ID is implicit.
 */
export default function ExtensionIdSettings() {
  const [extensionId, setLocalId] = useState<string | null>(() => getExtensionId());
  const [draft, setDraft] = useState<string>(() => getExtensionId() ?? "");
  const [editing, setEditing] = useState(false);

  useEffect(() => {
    const unsub = subscribeExtensionId((id) => {
      setLocalId(id);
      if (!editing) setDraft(id ?? "");
    });
    return unsub;
  }, [editing]);

  if (isExtensionContext()) return null;

  const detected = extensionId != null && extensionId.length > 0;

  return (
    <details className="mt-4 text-xs">
      <summary className="cursor-pointer text-fg-faint hover:text-fg-muted select-none">
        Extension ID:{" "}
        {detected ? (
          <span className="font-mono text-fg-muted">
            {extensionId?.slice(0, 8)}…{extensionId?.slice(-4)}
          </span>
        ) : (
          <span className="text-destructive">not set</span>
        )}
      </summary>
      <div className="mt-2 space-y-2">
        <p className="text-fg-faint">
          Auto-detected from the extension's content script on this page. Override below if
          detection fails (e.g. content script blocked).
        </p>
        {editing ? (
          <div className="flex gap-2">
            <input
              type="text"
              value={draft}
              onChange={(e) => setDraft(e.target.value.trim())}
              placeholder="abcdefghijklmnopabcdefghijklmnop"
              className="flex-1 rounded-md border border-edge bg-surface px-2 py-1 font-mono text-fg"
              autoComplete="off"
              spellCheck={false}
            />
            <button
              type="button"
              onClick={() => {
                setExtensionId(draft.length > 0 ? draft : null);
                setEditing(false);
              }}
              className="rounded-md bg-primary px-2 py-1 text-primary-fg hover:bg-primary-hover"
            >
              Save
            </button>
            <button
              type="button"
              onClick={() => {
                setDraft(extensionId ?? "");
                setEditing(false);
              }}
              className="rounded-md border border-edge px-2 py-1 text-fg-muted hover:text-fg"
            >
              Cancel
            </button>
          </div>
        ) : (
          <button
            type="button"
            onClick={() => setEditing(true)}
            className="rounded-md border border-edge px-2 py-1 text-fg-muted hover:text-fg"
          >
            {detected ? "Override" : "Set extension ID"}
          </button>
        )}
      </div>
    </details>
  );
}

// src/features/auth/ExtensionIdSettings.vue
<script setup lang="ts">
/**
 * Lets the user view or manually paste the chrome extension ID when the app is
 * running outside the extension (dev server, pages.dev). Hidden when running as
 * the extension's own page since the ID is implicit.
 */

import { onMounted, onUnmounted, ref } from "vue";
import {
  getExtensionId,
  isExtensionContext,
  setExtensionId,
  subscribeExtensionId,
} from "../../lib/extensionId";
import UiButton from "../../ui/Button.vue";

const extensionId = ref<string | null>(getExtensionId());
const draft = ref<string>(getExtensionId() ?? "");
const editing = ref(false);
const saved = ref(false);

let unsub: (() => void) | null = null;

onMounted(() => {
  unsub = subscribeExtensionId((id) => {
    extensionId.value = id;
    if (!editing.value) draft.value = id ?? "";
  });
});

onUnmounted(() => {
  unsub?.();
});

const detected = () =>
  extensionId.value !== null && extensionId.value.length > 0;

function save(): void {
  const trimmed = draft.value.trim();
  setExtensionId(trimmed.length > 0 ? trimmed : null);
  editing.value = false;
  saved.value = true;
  setTimeout(() => {
    saved.value = false;
  }, 1500);
}

function cancel(): void {
  draft.value = extensionId.value ?? "";
  editing.value = false;
}
</script>

<template>
  <details v-if="!isExtensionContext()" class="mt-4 text-xs">
    <summary class="cursor-pointer text-fg-faint hover:text-fg-muted select-none">
      Extension ID:
      <span v-if="detected()" class="font-mono text-fg-muted">
        {{ extensionId?.slice(0, 8) }}&hellip;{{ extensionId?.slice(-4) }}
      </span>
      <span v-else class="text-destructive">not set</span>
    </summary>

    <div class="mt-2 space-y-2">
      <p class="text-fg-faint">
        Auto-detected from the extension's content script on this page. Override
        below if detection fails (e.g. content script blocked).
      </p>

      <!-- Edit mode -->
      <div v-if="editing" class="flex gap-2">
        <input
          type="text"
          v-model="draft"
          placeholder="abcdefghijklmnopabcdefghijklmnop"
          class="flex-1 rounded-md border border-edge bg-surface px-2 py-1 font-mono text-fg"
          autocomplete="off"
          spellcheck="false"
        />
        <UiButton variant="primary" size="xs" @click="save">Save</UiButton>
        <UiButton variant="outline" size="xs" @click="cancel">Cancel</UiButton>
      </div>

      <!-- View mode -->
      <div v-else class="flex items-center gap-2">
        <UiButton variant="outline" size="xs" @click="editing = true">
          {{ detected() ? "Override" : "Set extension ID" }}
        </UiButton>
        <UiButton
          v-if="detected()"
          variant="ghost"
          size="xs"
          @click="setExtensionId(null)"
        >
          Clear
        </UiButton>
        <span v-if="saved" class="text-success text-[11px]">Saved</span>
      </div>
    </div>
  </details>
</template>
