// src/features/current/CurrentScheduleEditor.vue
<script setup lang="ts">
/**
 * Displays the student's currently-registered sections on a calendar and lets
 * them swap any course to a different section or toggle the course off the
 * calendar entirely. Placed on the Current tab in MainArea.
 */

import { computed } from "vue";
import { resolveCurrentSection } from "../../domain/conflicts";
import { formatTimeCompact } from "../../domain/time";
import type { CourseSection, CurrentRegistration, Schedule } from "../../domain/types";
import Card from "../../ui/Card.vue";
import CalendarGrid from "@/features/schedules/CalendarGrid.vue";

const props = defineProps<{
  currentRegistrations: Map<string, CurrentRegistration>;
  courseGroups: Map<string, CourseSection[]>;
  includedCourses: Set<string>;
  sectionOverrides: Map<string, string>;
}>();

const emit = defineEmits<{
  "swap-section": [subjectCourse: string, newSectionId: string];
  "toggle-course": [subjectCourse: string];
}>();

/** Build a Schedule-shaped object from the current registrations for CalendarGrid. */
const schedule = computed<Schedule>(() => {
  const courses: CourseSection[] = [];
  for (const subjectCourse of props.currentRegistrations.keys()) {
    if (!props.includedCourses.has(subjectCourse)) continue;
    const section = resolveCurrentSection(
      subjectCourse,
      props.currentRegistrations,
      props.sectionOverrides,
      props.courseGroups,
    );
    if (section) courses.push(section);
  }
  return {
    id: 0,
    qualityScore: 0,
    warnings: [],
    courses,
    daysUsed: [],
    daysCount: 0,
    onCampusDays: [],
    onCampusDaysCount: 0,
    onCampusPerDay: {},
    earlyMorningPenalty: 0,
    travelTimePenalty: 0,
    isPartial: false,
    omittedCourses: [],
    blockoutFitScore: 0,
  };
});

function getActiveSectionId(subjectCourse: string): string {
  const override = props.sectionOverrides.get(subjectCourse);
  if (override !== undefined) return override;
  const reg = props.currentRegistrations.get(subjectCourse);
  return reg?.currentSection.identifier ?? "";
}

function meetingSummary(section: CourseSection): string {
  return section.meetings
    .map((m) => `${m.days.join("")} ${formatTimeCompact(m.startTime)}–${formatTimeCompact(m.endTime)}`)
    .join(", ");
}

function onSelectChange(subjectCourse: string, event: Event): void {
  const target = event.target as HTMLSelectElement;
  emit("swap-section", subjectCourse, target.value);
}
</script>

<template>
  <div class="space-y-4">
    <!-- Calendar overview -->
    <CalendarGrid :schedule="schedule" />

    <!-- Per-course cards -->
    <div
      v-if="currentRegistrations.size > 0"
      class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3"
    >
      <Card
        v-for="[subjectCourse, reg] in currentRegistrations.entries()"
        :key="subjectCourse"
        padding="p-3"
        :class="includedCourses.has(subjectCourse) ? '' : 'opacity-60'"
      >
        <!-- Header: identifier + include toggle -->
        <div class="flex items-center gap-2 mb-2">
          <input
            type="checkbox"
            :checked="includedCourses.has(subjectCourse)"
            :aria-label="`Include ${subjectCourse} on calendar`"
            class="rounded border-edge-hover bg-surface-hover text-primary focus:ring-ring focus:ring-offset-0 shrink-0"
            @change="emit('toggle-course', subjectCourse)"
          />
          <span class="font-mono font-semibold text-sm text-fg leading-tight">
            {{ subjectCourse }}
          </span>
          <span class="text-xs text-fg-faint truncate flex-1 min-w-0">
            {{ reg.currentSection.title }}
          </span>
        </div>

        <!-- Section selector -->
        <div class="mb-2">
          <label :for="`section-select-${subjectCourse}`" class="sr-only">
            Section for {{ subjectCourse }}
          </label>
          <select
            :id="`section-select-${subjectCourse}`"
            :value="getActiveSectionId(subjectCourse)"
            class="w-full rounded-md border border-edge bg-surface px-2 py-1 text-xs text-fg focus:outline-none focus:ring-1 focus:ring-ring"
            @change="onSelectChange(subjectCourse, $event)"
          >
            <option
              v-for="section in courseGroups.get(subjectCourse) ?? []"
              :key="section.identifier"
              :value="section.identifier"
            >
              {{ section.identifier }}
            </option>
          </select>
        </div>

        <!-- Meeting summary for the active section -->
        <template
          v-for="section in [resolveCurrentSection(subjectCourse, currentRegistrations, sectionOverrides, courseGroups)]"
          :key="section?.identifier ?? `none-${subjectCourse}`"
        >
          <p v-if="section" class="text-[0.6875rem] text-fg-faint leading-snug">
            {{ meetingSummary(section) }}
          </p>
          <p v-else class="text-[0.6875rem] text-fg-faint italic">
            Section not found
          </p>
        </template>
      </Card>
    </div>

    <p v-else class="text-sm text-fg-faint text-center py-6">
      No registered courses found.
    </p>
  </div>
</template>

// src/components/CurrentScheduleEditor.tsx
import { useMemo, useState } from "react";
import { formatTime } from "../domain/time";
import type { CourseSection, CurrentRegistration } from "../lib/types";
import { resolveCurrentSection } from "../lib/types";
import CalendarGrid from "./CalendarGrid";

interface Props {
  currentRegistrations: Map<string, CurrentRegistration>;
  courseGroups: Map<string, CourseSection[]>;
  includedCourses: Set<string>;
  sectionOverrides: Map<string, string>;
  onSwapSection: (
    subjectCourse: string,
    newSectionId: string,
  ) => { success: boolean; conflicts: CourseSection[] };
  onToggleCourse: (subjectCourse: string) => void;
}

function formatMeetingTime(course: CourseSection): string {
  const meeting = course.meetings[0];
  if (!meeting) return "No scheduled meetings";

  const days = meeting.days.join("");
  const time = `${formatTime(meeting.startTime)}-${formatTime(meeting.endTime)}`;
  return `${days} ${time}`;
}

export default function CurrentScheduleEditor({
  currentRegistrations,
  courseGroups,
  includedCourses,
  sectionOverrides,
  onSwapSection,
  onToggleCourse,
}: Props) {
  const [conflicts, setConflicts] = useState<Map<string, CourseSection[]>>(new Map());

  // Build current schedule from registrations + overrides
  const currentScheduleCourses = useMemo(() => {
    const courses: CourseSection[] = [];
    for (const subjectCourse of currentRegistrations.keys()) {
      if (!includedCourses.has(subjectCourse)) continue;
      const section = resolveCurrentSection(
        subjectCourse,
        currentRegistrations,
        sectionOverrides,
        courseGroups,
      );
      if (section) courses.push(section);
    }
    return courses;
  }, [currentRegistrations, includedCourses, sectionOverrides, courseGroups]);

  const handleSwapSection = (subjectCourse: string, newSectionId: string) => {
    const result = onSwapSection(subjectCourse, newSectionId);
    if (!result.success) return;

    if (result.conflicts.length > 0) {
      const conflictMap = new Map(conflicts);
      conflictMap.set(subjectCourse, result.conflicts);
      setConflicts(conflictMap);
    } else {
      const conflictMap = new Map(conflicts);
      conflictMap.delete(subjectCourse);
      setConflicts(conflictMap);
    }
  };

  return (
    <div className="space-y-3">
      <p className="text-xs text-gray-500">
        {includedCourses.size} course{includedCourses.size !== 1 ? "s" : ""} selected
      </p>

      {/* Conflicts warning */}
      {conflicts.size > 0 && (
        <div className="rounded-lg bg-red-900/20 border border-red-800/50 px-3 py-2">
          <p className="text-xs text-red-400">
            &#x26A0;&#xFE0F; {conflicts.size} course{conflicts.size !== 1 ? "s" : ""} has scheduling
            conflict{conflicts.size !== 1 ? "s" : ""}
          </p>
        </div>
      )}

      {/* Calendar */}
      <div className="rounded-lg bg-gray-800/50 border border-gray-700 p-3">
        <CalendarGrid
          schedule={{
            id: 0,
            qualityScore: 0,
            warnings: [],
            courses: currentScheduleCourses,
            daysUsed: [],
            daysCount: 0,
            onCampusDays: [],
            onCampusDaysCount: 0,
            onCampusPerDay: {},
            earlyMorningPenalty: 0,
            travelTimePenalty: 0,
            isPartial: false,
            omittedCourses: [],
            blockoutFitScore: 0,
          }}
        />
      </div>

      {/* Course grid */}
      {currentRegistrations.size === 0 ? (
        <div className="text-xs text-gray-500 py-4 text-center">No courses loaded yet</div>
      ) : (
        <div className="grid grid-cols-1 sm:grid-cols-[repeat(auto-fit,minmax(13rem,1fr))] gap-3 xl:grid-cols-3">
          {Array.from(currentRegistrations.keys()).map((subjectCourse) => {
            const currentSection = resolveCurrentSection(
              subjectCourse,
              currentRegistrations,
              sectionOverrides,
              courseGroups,
            );

            const isIncluded = includedCourses.has(subjectCourse);
            const courseConflicts = conflicts.get(subjectCourse);
            const hasConflict = !!courseConflicts && courseConflicts.length > 0;

            if (!currentSection) return null;

            return (
              <div
                key={subjectCourse}
                className={`rounded-lg border p-3 transition-colors ${
                  hasConflict
                    ? "bg-red-900/20 border-red-800/50"
                    : isIncluded
                      ? "bg-gray-800 border-gray-700 hover:border-gray-600"
                      : "bg-gray-900/50 border-gray-700 opacity-60"
                }`}
              >
                {/* Course header */}
                <div className="flex items-start justify-between gap-2 mb-2">
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-1.5 flex-wrap">
                      <h4 className="text-sm font-semibold text-white">{subjectCourse}</h4>
                      <span className="text-xs bg-blue-900/50 text-blue-300 px-1.5 py-0.5 rounded">
                        {currentSection.sequenceNumber}
                      </span>
                    </div>
                    <p className="text-xs text-gray-400 mt-0.5 truncate">{currentSection.title}</p>
                  </div>
                  <label className="flex items-center gap-1.5 cursor-pointer shrink-0">
                    <input
                      type="checkbox"
                      checked={isIncluded}
                      onChange={() => onToggleCourse(subjectCourse)}
                      className="w-4 h-4 cursor-pointer"
                    />
                  </label>
                </div>

                {/* Meeting info */}
                <div className="text-xs text-gray-400 mb-2">
                  {formatMeetingTime(currentSection)}
                </div>

                {/* Conflict warning */}
                {hasConflict && (
                  <div className="mb-2 text-xs text-red-400 bg-red-900/20 rounded px-2 py-1">
                    &#x274C; Conflicts with:{" "}
                    {courseConflicts.map((c) => c.subjectCourse).join(", ")}
                  </div>
                )}

                {/* Section selector */}
                <select
                  value={sectionOverrides.get(subjectCourse) || currentSection.identifier}
                  onChange={(e) => handleSwapSection(subjectCourse, e.target.value)}
                  className="w-full bg-gray-900 border border-gray-700 rounded px-2 py-1 text-xs text-gray-300 hover:border-gray-600 focus:border-blue-500 focus:outline-none"
                >
                  {courseGroups.get(subjectCourse)?.map((section) => (
                    <option key={section.identifier} value={section.identifier}>
                      Section {section.sequenceNumber} - {formatMeetingTime(section)}
                    </option>
                  ))}
                </select>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
