// src/CoursesPanel.tsx
import { useAuth } from "./auth";
import CourseSearch from "./features/search/CourseSearch";
import CourseSelector from "./features/selection/CourseSelector";
import { useStore } from "./store";

interface Props {
  open: boolean;
}

/**
 * The expandable "Courses" panel — search input on the left, selected
 * course grid on the right. Hidden until the user toggles it open via
 * AppHeader.
 */
export default function CoursesPanel({ open }: Props) {
  const isLoggedIn = useAuth().status === "authenticated";
  const courseGroups = useStore((s) => s.courseGroups);
  const selectedCourses = useStore((s) => s.selectedCourses);
  const toggleCourse = useStore((s) => s.toggleCourse);
  const removeCourse = useStore((s) => s.removeCourse);

  if (!open || !isLoggedIn) return null;

  return (
    <div className="sticky top-12 z-10 border-b border-edge bg-surface/95 backdrop-blur-sm">
      <div className="max-w-screen-2xl mx-auto px-3 sm:px-4 py-3">
        <div className="flex flex-col sm:flex-row gap-4 sm:gap-6">
          <div className="sm:w-72 sm:shrink-0">
            <CourseSearch />
          </div>

          {courseGroups.size > 0 && (
            <div className="flex-1 min-w-0 sm:border-l border-edge-subtle sm:pl-6">
              <CourseSelector
                courseGroups={courseGroups}
                selectedCourses={selectedCourses}
                onToggle={toggleCourse}
                onRemove={removeCourse}
              />
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

// src/shell/CoursesPanel.vue
<script setup lang="ts">
import { storeToRefs } from "pinia";
import CourseSearch from "@/features/search/CourseSearch.vue";
import CourseSelector from "@/features/selection/CourseSelector.vue";
import { useCoursesStore } from "@/features/courses/store";
import { useSelectionStore } from "@/features/selection/store";

/**
 * Expandable panel under the header. Houses the search input on the
 * left and a grid of selected courses on the right. Hidden until the
 * header toggle opens it; collapses on mobile by stacking vertically.
 */
defineProps<{ open: boolean }>();

const coursesStore = useCoursesStore();
const { courseGroups } = storeToRefs(coursesStore);

const selectionStore = useSelectionStore();
const { selectedCourses } = storeToRefs(selectionStore);
</script>

<template>
  <div
    v-if="open"
    class="sticky top-12 z-10 border-b border-edge bg-surface/95 backdrop-blur-sm"
  >
    <div class="max-w-screen-2xl mx-auto px-3 sm:px-4 py-3">
      <div class="flex flex-col sm:flex-row gap-4 sm:gap-6">
        <div class="sm:w-72 sm:shrink-0">
          <CourseSearch />
        </div>
        <div
          v-if="courseGroups.size > 0"
          class="flex-1 min-w-0 sm:border-l border-edge-subtle sm:pl-6"
        >
          <CourseSelector
            :course-groups="courseGroups"
            :selected-courses="selectedCourses"
            @toggle="selectionStore.toggleCourse"
            @remove="coursesStore.removeCourse"
          />
        </div>
      </div>
    </div>
  </div>
</template>
