// src/App.tsx
import { useState } from "react";
import AppHeader from "./AppHeader";
import { useAuth, useAuthInit } from "./auth";
import CoursesPanel from "./CoursesPanel";
import { useHolds } from "./holds";
import { useDemoBootstrap } from "./hooks/useDemoBootstrap";
import { useScheduleSync } from "./hooks/useScheduleSync";
import { useIdentity } from "./identity";
import { useExtensionIdListener } from "./lib/extensionIdListener";
import MainArea from "./MainArea";
import { useProfile } from "./profile";
import { useRegistrationStatus } from "./registration-status";
import SignInScreen from "./SignInScreen";

export default function App() {
  useExtensionIdListener();
  useDemoBootstrap();
  useAuthInit();
  useIdentity();
  useScheduleSync();
  useProfile();
  useRegistrationStatus();
  useHolds();

  const { status } = useAuth();
  const [panelOpen, setPanelOpen] = useState(true);

  if (status !== "authenticated") return <SignInScreen />;

  return (
    <div className="min-h-screen bg-page text-fg">
      <AppHeader panelOpen={panelOpen} onTogglePanel={() => setPanelOpen((v) => !v)} />
      <CoursesPanel open={panelOpen} />
      <MainArea />
    </div>
  );
}

// src/App.vue
<script setup lang="ts">
import { computed } from "vue";
import { useAuthStore } from "./auth/store";
import { useAuthInit } from "./auth/useAuthInit";
import { useDemoBootstrap } from "./composables/useDemoBootstrap";
import { useScheduleSync } from "./composables/useScheduleSync";
import { useHolds } from "./holds/useHolds";
import { useIdentity } from "./identity/useIdentity";
import { useExtensionIdListener } from "./lib/extensionIdListener";
import { useProfile } from "./profile/useProfile";
import { useRegistrationStatus } from "./registration-status/useRegistrationStatus";
import AppShell from "./shell/AppShell.vue";
import SignInScreen from "./shell/SignInScreen.vue";
import { useTheme } from "./theme/useTheme";

// Side-effect composables — mounted once at the root.
useExtensionIdListener();
useAuthInit();
useScheduleSync();
useDemoBootstrap();
useTheme();
useIdentity();
useProfile();
useHolds();
useRegistrationStatus();

const auth = useAuthStore();
const authenticated = computed(() => auth.status === "authenticated");
</script>

<template>
  <SignInScreen v-if="!authenticated" />
  <AppShell v-else />
</template>
