// src/shell/SignInScreen.vue
<script setup lang="ts">
import { useAuth } from "@/features/auth/useAuth";
import ExtensionIdSettings from "@/features/auth/ExtensionIdSettings.vue";
import ThemePicker from "@/features/theme/ThemePicker.vue";
import Card from "@/ui/Card.vue";
import UiButton from "@/ui/Button.vue";

const { busy, error, login, cancelLogin } = useAuth();

async function handleLogin(): Promise<void> {
  await login();
}
</script>

<template>
  <div class="flex items-center justify-center min-h-screen bg-page text-fg p-4">
    <Card size="sm">
      <div class="flex items-center justify-between mb-3">
        <h1 class="text-sm font-medium text-fg-muted">Connect to SAIT Banner</h1>
        <ThemePicker />
      </div>
      <p class="text-xs text-fg-faint mb-4">
        A SAIT login window will open. Sign in and it will close automatically.
      </p>
      <UiButton
        variant="primary"
        size="md"
        :disabled="busy"
        class="w-full"
        @click="handleLogin"
      >
        {{ busy ? "Waiting for SAIT login…" : "Sign in with SAIT" }}
      </UiButton>
      <UiButton
        v-if="busy"
        variant="outline"
        size="xs"
        class="mt-2 w-full"
        @click="cancelLogin"
      >
        Cancel
      </UiButton>
      <p v-if="error" class="mt-3 text-xs text-destructive">{{ error }}</p>
      <ExtensionIdSettings />
    </Card>
  </div>
</template>

// src/SignInScreen.tsx
import { useAuth } from "./auth";
import ExtensionIdSettings from "./features/auth/ExtensionIdSettings";
import ThemePicker from "./features/theme/ThemePicker";
import Card from "./ui/Card";

export default function SignInScreen() {
  const { busy, error, login } = useAuth();

  return (
    <div className="flex items-center justify-center min-h-screen bg-page text-fg p-4">
      <Card size="sm">
        <div className="flex items-center justify-between mb-3">
          <h3 className="text-sm font-medium text-fg-muted">Connect to SAIT Banner</h3>
          <ThemePicker />
        </div>
        <p className="text-xs text-fg-faint mb-4">
          A SAIT login window will open. Sign in and it will close automatically.
        </p>
        <button
          type="button"
          onClick={() => void login()}
          disabled={busy}
          className="w-full rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-fg hover:bg-primary-hover disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
        >
          {busy ? "Waiting for SAIT login…" : "Sign in with SAIT"}
        </button>
        {error && <p className="mt-3 text-xs text-destructive">{error}</p>}
        <ExtensionIdSettings />
      </Card>
    </div>
  );
}
